CREATE TABLE FOURNISSEUR (
  ID_FOURNISSEUR VARCHAR2(50) PRIMARY KEY,
  NOM VARCHAR2(100) NOT NULL,
  TYPE_MATIERE VARCHAR2(50),
  TELEPHONE VARCHAR2(20),
  ADRESSE VARCHAR2(255),
  DELAI_LIVRAISON VARCHAR2(20),
  QUALITE VARCHAR2(50),
  STATUT VARCHAR2(50)
);
