$conn = New-Object System.Data.Odbc.OdbcConnection
$conn.ConnectionString = 'DSN=youssef;Uid=smartleather;Pwd=smartleather;'
$conn.Open()

$queries = @(
    "ALTER TABLE FOURNISSEUR ADD PRIMARY KEY (ID_FOURNISSEUR)",
    "ALTER TABLE MATIEREPREMIER ADD PRIMARY KEY (ID_MATIERE)",
    "ALTER TABLE PRODUIT ADD PRIMARY KEY (ID_PRODUIT)",
    "ALTER TABLE COMMANDE ADD PRIMARY KEY (ID_COMMANDE)",
    "ALTER TABLE EMPLOYEE ADD PRIMARY KEY (ID_EMPLOYEE)",
    "ALTER TABLE MACHINE ADD PRIMARY KEY (ID_MACHINE)",
    "CREATE TABLE FOURNIR_MATIERE (ID_FOURNISSEUR VARCHAR2(50), ID_MATIERE VARCHAR2(50), PRIMARY KEY (ID_FOURNISSEUR, ID_MATIERE), FOREIGN KEY (ID_FOURNISSEUR) REFERENCES FOURNISSEUR(ID_FOURNISSEUR), FOREIGN KEY (ID_MATIERE) REFERENCES MATIEREPREMIER(ID_MATIERE))",
    "CREATE TABLE PRODUIT_MATIERE (ID_PRODUIT VARCHAR2(50), ID_MATIERE VARCHAR2(50), QUANTITE NUMBER, PRIMARY KEY (ID_PRODUIT, ID_MATIERE), FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT(ID_PRODUIT), FOREIGN KEY (ID_MATIERE) REFERENCES MATIEREPREMIER(ID_MATIERE))",
    "CREATE TABLE LIGNE_COMMANDE (ID_COMMANDE VARCHAR2(50), ID_PRODUIT VARCHAR2(50), QUANTITE NUMBER, PRIMARY KEY (ID_COMMANDE, ID_PRODUIT), FOREIGN KEY (ID_COMMANDE) REFERENCES COMMANDE(ID_COMMANDE), FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT(ID_PRODUIT))",
    "CREATE TABLE EMPLOYE_MACHINE (ID_EMPLOYEE VARCHAR2(50), ID_MACHINE VARCHAR2(50), PRIMARY KEY (ID_EMPLOYEE, ID_MACHINE), FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE(ID_EMPLOYEE), FOREIGN KEY (ID_MACHINE) REFERENCES MACHINE(ID_MACHINE))"
)

foreach ($q in $queries) {
    try {
        $cmd = $conn.CreateCommand()
        $cmd.CommandText = $q
        $cmd.ExecuteNonQuery()
        Write-Output ("Success: " + $q.Substring(0, 30))
    } catch {
        Write-Output ("Error: " + $_.Exception.Message)
    }
}
$conn.Close()
