CREATE TABLE EMPLOYE (
  ID_EMPLOYE     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOM            VARCHAR2(80) NOT NULL,
  PRENOM         VARCHAR2(80) NOT NULL,
  DATE_NAISSANCE DATE,
  POSTE          VARCHAR2(80),
  SALAIRE        NUMBER(10,2) DEFAULT 0
);
