CREATE TABLE EMPLOYE (
  ID_EMPLOYE     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOM            VARCHAR2(80) NOT NULL,
  PRENOM         VARCHAR2(80) NOT NULL,
  DATE_NAISSANCE DATE,
  POSTE          VARCHAR2(80),
  SALAIRE        NUMBER(10,2) DEFAULT 0
);

CREATE TABLE MATIERE (
  ID_MATIERE VARCHAR2(20) PRIMARY KEY,
  TYPE_MATIERE VARCHAR2(80),
  COULEUR VARCHAR2(50),
  QUALITE VARCHAR2(50),
  PRIX NUMBER(10,2),
  STOCK NUMBER,
  FOURNISSEUR VARCHAR2(100)
);
